/*
  Every Thread in Java has some name , it may be default or customized name generated by jvm or customized name provided by Programmer .
  We can set or get names of Thread by using the following two Methods of "Thread" Class.
  public final String getName() 
  public final String setName(String name)
 */
 class MyThread1 extends Thread
 {
 }
 
 class ThreadDemo
 {
   public static void main(String arr[])
   { 
     MyThread1 t = new MyThread1() ;

     System.out.println(Thread.currentThread().getName()) ;
     Thread.currentThread().setName("OO yeah") ; 
     System.out.println(t.getName()) ;
     t.setName("Oo Haa");
     System.out.println(t.getName()) ;
     System.out.println(Thread.currentThread().getName());
   }
 }
 
